package compile_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/suite"

	rcfg "github.com/kalo-build/morphe-go/pkg/registry/cfg"
	"github.com/kalo-build/plugin-morphe-ts-zod-bridge/internal/testutils"
	"github.com/kalo-build/plugin-morphe-ts-zod-bridge/pkg/compile"
	"github.com/kalo-build/plugin-morphe-ts-zod-bridge/pkg/compile/cfg"
)

type CompileIntegrationTestSuite struct {
	suite.Suite

	TestDirPath       string
	ModelsDirPath     string
	EnumsDirPath      string
	StructuresDirPath string
	EntitiesDirPath   string
}

func TestCompileIntegrationTestSuite(t *testing.T) {
	suite.Run(t, new(CompileIntegrationTestSuite))
}

func (s *CompileIntegrationTestSuite) SetupTest() {
	s.TestDirPath = testutils.GetTestDirPath()
	s.ModelsDirPath = filepath.Join(s.TestDirPath, "registry", "minimal", "models")
	s.EnumsDirPath = filepath.Join(s.TestDirPath, "registry", "minimal", "enums")
	s.StructuresDirPath = filepath.Join(s.TestDirPath, "registry", "minimal", "structures")
	s.EntitiesDirPath = filepath.Join(s.TestDirPath, "registry", "minimal", "entities")
}

func (s *CompileIntegrationTestSuite) TestMorpheToBridge_FullRegistry_SnakeToCamel() {
	// Arrange
	outputDir := filepath.Join(s.TestDirPath, "working-integration-full")
	s.Nil(os.Mkdir(outputDir, 0755))
	defer os.RemoveAll(outputDir)

	config := compile.BridgeConfig{
		MorpheLoadRegistryConfig: rcfg.MorpheLoadRegistryConfig{
			RegistryModelsDirPath:     s.ModelsDirPath,
			RegistryEnumsDirPath:      s.EnumsDirPath,
			RegistryStructuresDirPath: s.StructuresDirPath,
			RegistryEntitiesDirPath:   s.EntitiesDirPath,
		},
		OutputPath:           outputDir,
		SourceCasing:         cfg.CasingSnake,
		TargetCasing:         cfg.CasingCamel,
		ZodSchemasImportPath: "@/generated/schemas",
		TsTypesImportPath:    "@/generated/types",
	}

	// Act
	err := compile.MorpheToBridge(config)

	// Assert
	s.NoError(err)

	// Verify model converters exist
	s.FileExists(filepath.Join(outputDir, "models", "person.ts"))
	s.FileExists(filepath.Join(outputDir, "models", "company.ts"))
	s.FileExists(filepath.Join(outputDir, "models", "contact-info.ts"))

	// Verify structure converters exist
	s.FileExists(filepath.Join(outputDir, "structures", "address.ts"))

	// Verify entity converters exist
	s.FileExists(filepath.Join(outputDir, "entities", "person.ts"))
	s.FileExists(filepath.Join(outputDir, "entities", "company.ts"))
}

func (s *CompileIntegrationTestSuite) TestMorpheToBridge_AllFilesHaveGeneratedHeader() {
	// Arrange
	outputDir := filepath.Join(s.TestDirPath, "working-integration-headers")
	s.Nil(os.Mkdir(outputDir, 0755))
	defer os.RemoveAll(outputDir)

	config := compile.BridgeConfig{
		MorpheLoadRegistryConfig: rcfg.MorpheLoadRegistryConfig{
			RegistryModelsDirPath:     s.ModelsDirPath,
			RegistryEnumsDirPath:      s.EnumsDirPath,
			RegistryStructuresDirPath: s.StructuresDirPath,
			RegistryEntitiesDirPath:   s.EntitiesDirPath,
		},
		OutputPath:           outputDir,
		SourceCasing:         cfg.CasingSnake,
		TargetCasing:         cfg.CasingCamel,
		ZodSchemasImportPath: "@/generated/schemas",
		TsTypesImportPath:    "@/generated/types",
	}

	// Act
	err := compile.MorpheToBridge(config)
	s.NoError(err)

	// Assert: all generated files start with the header comment
	allFiles := []string{
		filepath.Join(outputDir, "models", "person.ts"),
		filepath.Join(outputDir, "models", "company.ts"),
		filepath.Join(outputDir, "structures", "address.ts"),
		filepath.Join(outputDir, "entities", "person.ts"),
		filepath.Join(outputDir, "entities", "company.ts"),
	}

	for _, filePath := range allFiles {
		content, readErr := os.ReadFile(filePath)
		s.NoError(readErr, "failed to read %s", filePath)
		s.Contains(string(content), "// Code generated by plugin-morphe-ts-zod-bridge. DO NOT EDIT.",
			"file %s missing generated header", filePath)
	}
}

func (s *CompileIntegrationTestSuite) TestMorpheToBridge_EmptyRegistryProducesNoOutput() {
	// Arrange: registry with empty directories produces no converter files
	emptyRegDir := filepath.Join(s.TestDirPath, "working-integration-empty-reg")
	s.Nil(os.MkdirAll(filepath.Join(emptyRegDir, "models"), 0755))
	s.Nil(os.MkdirAll(filepath.Join(emptyRegDir, "enums"), 0755))
	s.Nil(os.MkdirAll(filepath.Join(emptyRegDir, "structures"), 0755))
	s.Nil(os.MkdirAll(filepath.Join(emptyRegDir, "entities"), 0755))
	defer os.RemoveAll(emptyRegDir)

	outputDir := filepath.Join(s.TestDirPath, "working-integration-empty-out")
	s.Nil(os.Mkdir(outputDir, 0755))
	defer os.RemoveAll(outputDir)

	config := compile.BridgeConfig{
		MorpheLoadRegistryConfig: rcfg.MorpheLoadRegistryConfig{
			RegistryModelsDirPath:     filepath.Join(emptyRegDir, "models"),
			RegistryEnumsDirPath:      filepath.Join(emptyRegDir, "enums"),
			RegistryStructuresDirPath: filepath.Join(emptyRegDir, "structures"),
			RegistryEntitiesDirPath:   filepath.Join(emptyRegDir, "entities"),
		},
		OutputPath:           outputDir,
		SourceCasing:         cfg.CasingSnake,
		TargetCasing:         cfg.CasingCamel,
		ZodSchemasImportPath: "@/schemas",
		TsTypesImportPath:    "@/types",
	}

	// Act
	err := compile.MorpheToBridge(config)

	// Assert: no error, but no output files
	s.NoError(err)

	// Output directory should have no subdirectories
	entries, readErr := os.ReadDir(outputDir)
	s.NoError(readErr)
	s.Empty(entries)
}

func (s *CompileIntegrationTestSuite) TestBridgeConfig_Validate_MissingOutputPath() {
	// Arrange
	config := compile.BridgeConfig{
		MorpheLoadRegistryConfig: rcfg.MorpheLoadRegistryConfig{
			RegistryModelsDirPath:     s.ModelsDirPath,
			RegistryEnumsDirPath:      s.EnumsDirPath,
			RegistryStructuresDirPath: s.StructuresDirPath,
			RegistryEntitiesDirPath:   s.EntitiesDirPath,
		},
		OutputPath:           "",
		SourceCasing:         cfg.CasingSnake,
		TargetCasing:         cfg.CasingCamel,
		ZodSchemasImportPath: "@/schemas",
		TsTypesImportPath:    "@/types",
	}

	// Act
	err := config.Validate()

	// Assert
	s.Error(err)
	s.Contains(err.Error(), "output path is required")
}

func (s *CompileIntegrationTestSuite) TestBridgeConfig_Validate_InvalidSourceCasing() {
	// Arrange
	config := compile.BridgeConfig{
		MorpheLoadRegistryConfig: rcfg.MorpheLoadRegistryConfig{
			RegistryModelsDirPath:     s.ModelsDirPath,
			RegistryEnumsDirPath:      s.EnumsDirPath,
			RegistryStructuresDirPath: s.StructuresDirPath,
			RegistryEntitiesDirPath:   s.EntitiesDirPath,
		},
		OutputPath:           "/tmp/output",
		SourceCasing:         cfg.Casing("INVALID"),
		TargetCasing:         cfg.CasingCamel,
		ZodSchemasImportPath: "@/schemas",
		TsTypesImportPath:    "@/types",
	}

	// Act
	err := config.Validate()

	// Assert
	s.Error(err)
	s.Contains(err.Error(), "invalid casing value")
}

func (s *CompileIntegrationTestSuite) TestBridgeConfig_Validate_MissingZodImportPath() {
	// Arrange
	config := compile.BridgeConfig{
		MorpheLoadRegistryConfig: rcfg.MorpheLoadRegistryConfig{
			RegistryModelsDirPath:     s.ModelsDirPath,
			RegistryEnumsDirPath:      s.EnumsDirPath,
			RegistryStructuresDirPath: s.StructuresDirPath,
			RegistryEntitiesDirPath:   s.EntitiesDirPath,
		},
		OutputPath:           "/tmp/output",
		SourceCasing:         cfg.CasingSnake,
		TargetCasing:         cfg.CasingCamel,
		ZodSchemasImportPath: "",
		TsTypesImportPath:    "@/types",
	}

	// Act
	err := config.Validate()

	// Assert
	s.Error(err)
	s.Contains(err.Error(), "zodSchemasImportPath is required")
}

func (s *CompileIntegrationTestSuite) TestBridgeConfig_Validate_MissingTsImportPath() {
	// Arrange
	config := compile.BridgeConfig{
		MorpheLoadRegistryConfig: rcfg.MorpheLoadRegistryConfig{
			RegistryModelsDirPath:     s.ModelsDirPath,
			RegistryEnumsDirPath:      s.EnumsDirPath,
			RegistryStructuresDirPath: s.StructuresDirPath,
			RegistryEntitiesDirPath:   s.EntitiesDirPath,
		},
		OutputPath:           "/tmp/output",
		SourceCasing:         cfg.CasingSnake,
		TargetCasing:         cfg.CasingCamel,
		ZodSchemasImportPath: "@/schemas",
		TsTypesImportPath:    "",
	}

	// Act
	err := config.Validate()

	// Assert
	s.Error(err)
	s.Contains(err.Error(), "tsTypesImportPath is required")
}
