package compile_test

import (
	"testing"

	"github.com/stretchr/testify/suite"

	"github.com/kalo-build/plugin-morphe-ts-zod-bridge/pkg/compile"
	"github.com/kalo-build/plugin-morphe-ts-zod-bridge/pkg/compile/cfg"
)

type ConverterTestSuite struct {
	suite.Suite
}

func TestConverterTestSuite(t *testing.T) {
	suite.Run(t, new(ConverterTestSuite))
}

func (s *ConverterTestSuite) TestBuildFieldMappings_SnakeToCamel() {
	// Arrange
	fieldNames := []string{"FirstName", "LastName", "DateOfBirth"}

	// Act
	mappings := compile.BuildFieldMappings(fieldNames, cfg.CasingSnake, cfg.CasingCamel)

	// Assert
	s.Require().Len(mappings, 3)
	s.Equal("first_name", mappings[0].SourceName)
	s.Equal("firstName", mappings[0].TargetName)
	s.Equal("last_name", mappings[1].SourceName)
	s.Equal("lastName", mappings[1].TargetName)
	s.Equal("date_of_birth", mappings[2].SourceName)
	s.Equal("dateOfBirth", mappings[2].TargetName)
}

func (s *ConverterTestSuite) TestBuildFieldMappings_CamelToSnake() {
	// Arrange
	fieldNames := []string{"Email", "ZipCode"}

	// Act
	mappings := compile.BuildFieldMappings(fieldNames, cfg.CasingCamel, cfg.CasingSnake)

	// Assert
	s.Require().Len(mappings, 2)
	s.Equal("email", mappings[0].SourceName)
	s.Equal("email", mappings[0].TargetName)
	s.Equal("zipCode", mappings[1].SourceName)
	s.Equal("zip_code", mappings[1].TargetName)
}

func (s *ConverterTestSuite) TestBuildFieldMappings_SameCasing() {
	// Arrange
	fieldNames := []string{"FirstName", "LastName"}

	// Act
	mappings := compile.BuildFieldMappings(fieldNames, cfg.CasingCamel, cfg.CasingCamel)

	// Assert
	s.Require().Len(mappings, 2)
	s.Equal("firstName", mappings[0].SourceName)
	s.Equal("firstName", mappings[0].TargetName)
	s.Equal("lastName", mappings[1].SourceName)
	s.Equal("lastName", mappings[1].TargetName)
}

func (s *ConverterTestSuite) TestBuildFieldMappings_EmptyInput() {
	// Arrange & Act
	mappings := compile.BuildFieldMappings([]string{}, cfg.CasingSnake, cfg.CasingCamel)

	// Assert
	s.Empty(mappings)
}

func (s *ConverterTestSuite) TestBuildConverterData_ModelCategory() {
	// Arrange
	fieldNames := []string{"FirstName", "LastName"}
	config := compile.BridgeConfig{
		SourceCasing:         cfg.CasingSnake,
		TargetCasing:         cfg.CasingCamel,
		ZodSchemasImportPath: "@/generated/schemas",
		TsTypesImportPath:    "@/generated/types",
	}

	// Act
	data := compile.BuildConverterData("Person", "models", fieldNames, config)

	// Assert
	s.Equal("Person", data.TypeName)
	s.Equal("models", data.Category)
	s.Equal("convertPerson", data.FunctionName)
	s.Equal("PersonSchema", data.SchemaName)
	s.Equal("@/generated/types/models/person", data.TsTypeImportPath)
	s.Equal("@/generated/schemas/models/person", data.ZodSchemaImportPath)
	s.Require().Len(data.Fields, 2)
	s.Equal("first_name", data.Fields[0].SourceName)
	s.Equal("firstName", data.Fields[0].TargetName)
}

func (s *ConverterTestSuite) TestBuildConverterData_MultiWordTypeName() {
	// Arrange
	fieldNames := []string{"Street", "HouseNr"}
	config := compile.BridgeConfig{
		SourceCasing:         cfg.CasingSnake,
		TargetCasing:         cfg.CasingCamel,
		ZodSchemasImportPath: "@/schemas",
		TsTypesImportPath:    "@/types",
	}

	// Act
	data := compile.BuildConverterData("ContactInfo", "models", fieldNames, config)

	// Assert
	s.Equal("ContactInfo", data.TypeName)
	s.Equal("convertContactInfo", data.FunctionName)
	s.Equal("ContactInfoSchema", data.SchemaName)
	s.Equal("@/types/models/contact-info", data.TsTypeImportPath)
	s.Equal("@/schemas/models/contact-info", data.ZodSchemaImportPath)
}

func (s *ConverterTestSuite) TestRenderConverter_SnakeToCamel() {
	// Arrange
	data := compile.ConverterData{
		TypeName:            "Person",
		Category:            "models",
		FunctionName:        "convertPerson",
		SchemaName:          "PersonSchema",
		TsTypeImportPath:    "@/generated/types/models/person",
		ZodSchemaImportPath: "@/generated/schemas/models/person",
		Fields: []compile.FieldMapping{
			{SourceName: "first_name", TargetName: "firstName"},
			{SourceName: "last_name", TargetName: "lastName"},
		},
	}

	// Act
	content := compile.RenderConverter(data)
	contentStr := string(content)

	// Assert
	s.Contains(contentStr, "// Code generated by plugin-morphe-ts-zod-bridge. DO NOT EDIT.")
	s.Contains(contentStr, "import type { Person } from '@/generated/types/models/person';")
	s.Contains(contentStr, "import { PersonSchema } from '@/generated/schemas/models/person';")
	s.Contains(contentStr, "import { z } from 'zod';")
	s.Contains(contentStr, "export function convertPerson(")
	s.Contains(contentStr, "source: z.infer<typeof PersonSchema>")
	s.Contains(contentStr, "): Person {")
	s.Contains(contentStr, "firstName: source.first_name,")
	s.Contains(contentStr, "lastName: source.last_name,")
}

func (s *ConverterTestSuite) TestRenderConverter_EmptyFields() {
	// Arrange
	data := compile.ConverterData{
		TypeName:            "Empty",
		Category:            "models",
		FunctionName:        "convertEmpty",
		SchemaName:          "EmptySchema",
		TsTypeImportPath:    "@/types/models/empty",
		ZodSchemaImportPath: "@/schemas/models/empty",
		Fields:              []compile.FieldMapping{},
	}

	// Act
	content := compile.RenderConverter(data)
	contentStr := string(content)

	// Assert
	s.Contains(contentStr, "export function convertEmpty(")
	s.Contains(contentStr, "return {\n  };\n}")
}

func (s *ConverterTestSuite) TestRenderConverter_SingleField() {
	// Arrange
	data := compile.ConverterData{
		TypeName:            "Simple",
		Category:            "structures",
		FunctionName:        "convertSimple",
		SchemaName:          "SimpleSchema",
		TsTypeImportPath:    "@/types/structures/simple",
		ZodSchemaImportPath: "@/schemas/structures/simple",
		Fields: []compile.FieldMapping{
			{SourceName: "name", TargetName: "name"},
		},
	}

	// Act
	content := compile.RenderConverter(data)
	contentStr := string(content)

	// Assert
	s.Contains(contentStr, "name: source.name,")
	s.Contains(contentStr, "): Simple {")
}
