package compile

import (
	"fmt"
	"strings"

	"github.com/kalo-build/go-util/strcase"
	"github.com/kalo-build/plugin-morphe-ts-zod-bridge/pkg/compile/cfg"
)

// FieldMapping represents a single field name mapping from source to target casing.
type FieldMapping struct {
	// SourceName is the field name in source casing (e.g., "first_name" for snake).
	SourceName string
	// TargetName is the field name in target casing (e.g., "firstName" for camel).
	TargetName string
}

// ConverterData holds the template data for generating a converter function.
type ConverterData struct {
	// TypeName is the PascalCase name of the Morphe type (e.g., "Person").
	TypeName string
	// Category is the type category ("models", "structures", "entities").
	Category string
	// FunctionName is the camelCase converter function name (e.g., "convertPerson").
	FunctionName string
	// SchemaName is the camelCase schema variable name (e.g., "personSchema").
	SchemaName string
	// TsTypeImportPath is the full import path for the TS type.
	TsTypeImportPath string
	// ZodSchemaImportPath is the full import path for the Zod schema.
	ZodSchemaImportPath string
	// Fields is the list of field mappings.
	Fields []FieldMapping
}

// BuildFieldMappings converts a list of PascalCase field names into source/target
// casing field mappings using the configured casing functions.
func BuildFieldMappings(fieldNames []string, sourceCasing cfg.Casing, targetCasing cfg.Casing) []FieldMapping {
	mappings := make([]FieldMapping, 0, len(fieldNames))
	for _, name := range fieldNames {
		mappings = append(mappings, FieldMapping{
			SourceName: sourceCasing.Apply(name),
			TargetName: targetCasing.Apply(name),
		})
	}
	return mappings
}

// BuildConverterData constructs the full template data for a converter function.
func BuildConverterData(
	typeName string,
	category string,
	fieldNames []string,
	config BridgeConfig,
) ConverterData {
	kebabName := strings.ToLower(strcase.ToKebabCase(typeName))
	return ConverterData{
		TypeName:            typeName,
		Category:            category,
		FunctionName:        "convert" + typeName,
		SchemaName:          typeName + "Schema",
		TsTypeImportPath:    fmt.Sprintf("%s/%s/%s", config.TsTypesImportPath, category, kebabName),
		ZodSchemaImportPath: fmt.Sprintf("%s/%s/%s", config.ZodSchemasImportPath, category, kebabName),
		Fields:              BuildFieldMappings(fieldNames, config.SourceCasing, config.TargetCasing),
	}
}

// RenderConverter generates the TypeScript converter file content from converter data.
func RenderConverter(data ConverterData) []byte {
	var sb strings.Builder

	// Header
	sb.WriteString("// Code generated by plugin-morphe-ts-zod-bridge. DO NOT EDIT.\n")

	// Imports
	sb.WriteString(fmt.Sprintf("import type { %s } from '%s';\n", data.TypeName, data.TsTypeImportPath))
	sb.WriteString(fmt.Sprintf("import { %s } from '%s';\n", data.SchemaName, data.ZodSchemaImportPath))
	sb.WriteString("import { z } from 'zod';\n")

	// Function
	sb.WriteString("\n")
	sb.WriteString(fmt.Sprintf("export function %s(\n", data.FunctionName))
	sb.WriteString(fmt.Sprintf("  source: z.infer<typeof %s>\n", data.SchemaName))
	sb.WriteString(fmt.Sprintf("): %s {\n", data.TypeName))
	sb.WriteString("  return {\n")

	for _, field := range data.Fields {
		sb.WriteString(fmt.Sprintf("    %s: source.%s,\n", field.TargetName, field.SourceName))
	}

	sb.WriteString("  };\n")
	sb.WriteString("}\n")

	return []byte(sb.String())
}
