package compile

import (
	"fmt"
	"strings"

	"github.com/kalo-build/go-util/strcase"
	"github.com/kalo-build/plugin-morphe-ts-zod-bridge/pkg/compile/cfg"
)

// FieldInput describes a field to be included in a converter, carrying its
// PascalCase name, optionality flag, and an optional suffix (e.g. "s" for
// pluralised relationship fields in "Many" relations).
type FieldInput struct {
	// Name is the PascalCase field name (e.g. "FirstName", "CompanyID").
	Name string
	// Optional marks the field as optional in the generated converter.
	Optional bool
	// Suffix is appended to the cased field name (e.g. "s" for HasMany FK arrays).
	Suffix string
	// RelationTarget is the PascalCase target type name (e.g. "Organization")
	// for relationship object fields that need recursive conversion. Empty for
	// scalar fields and FK ID fields.
	RelationTarget string
	// IsArray indicates the relationship is a "Many" type, requiring .map()
	// instead of a direct converter call.
	IsArray bool
}

// FieldMapping represents a single field name mapping from source to target casing.
type FieldMapping struct {
	// SourceName is the field name in source casing (e.g., "first_name" for snake).
	SourceName string
	// TargetName is the field name in target casing (e.g., "firstName" for camel).
	TargetName string
	// Optional indicates whether this field should use conditional spread in the converter.
	Optional bool
	// ConverterFn is the converter function name for relationship object fields
	// (e.g., "convertOrganization"). Empty for scalar/FK ID fields.
	ConverterFn string
	// ConverterImport is the relative import path for the converter function
	// (e.g., "./organization"). Empty for scalar fields and self-references.
	ConverterImport string
	// IsArray indicates this is an array relationship field requiring .map().
	IsArray bool
}

// ConverterData holds the template data for generating a converter function.
type ConverterData struct {
	// TypeName is the PascalCase name of the Morphe type (e.g., "Person").
	TypeName string
	// Category is the type category ("models", "structures", "entities").
	Category string
	// FunctionName is the camelCase converter function name (e.g., "convertPerson").
	FunctionName string
	// SchemaName is the camelCase schema variable name (e.g., "personSchema").
	SchemaName string
	// TsTypeImportPath is the full import path for the TS type.
	TsTypeImportPath string
	// ZodSchemaImportPath is the full import path for the Zod schema.
	ZodSchemaImportPath string
	// Fields is the list of field mappings.
	Fields []FieldMapping
}

// BuildFieldMappings converts a list of FieldInput descriptors into source/target
// casing field mappings using the configured casing functions.
func BuildFieldMappings(fields []FieldInput, sourceCasing cfg.Casing, targetCasing cfg.Casing) []FieldMapping {
	mappings := make([]FieldMapping, 0, len(fields))
	for _, f := range fields {
		m := FieldMapping{
			SourceName: sourceCasing.Apply(f.Name) + f.Suffix,
			TargetName: targetCasing.Apply(f.Name) + f.Suffix,
			Optional:   f.Optional,
		}
		if f.RelationTarget != "" {
			m.ConverterFn = "convert" + f.RelationTarget
			m.ConverterImport = "./" + strings.ToLower(strcase.ToKebabCase(f.RelationTarget))
			m.IsArray = f.IsArray
		}
		mappings = append(mappings, m)
	}
	return mappings
}

// BuildConverterData constructs the full template data for a converter function.
func BuildConverterData(
	typeName string,
	category string,
	fields []FieldInput,
	config BridgeConfig,
) ConverterData {
	kebabName := strings.ToLower(strcase.ToKebabCase(typeName))
	return ConverterData{
		TypeName:            typeName,
		Category:            category,
		FunctionName:        "convert" + typeName,
		SchemaName:          typeName + "Schema",
		TsTypeImportPath:    fmt.Sprintf("%s/%s/%s", config.TsTypesImportPath, category, kebabName),
		ZodSchemaImportPath: fmt.Sprintf("%s/%s/%s", config.ZodSchemasImportPath, category, kebabName),
		Fields:              BuildFieldMappings(fields, config.SourceCasing, config.TargetCasing),
	}
}

// RenderConverter generates the TypeScript converter file content from converter data.
func RenderConverter(data ConverterData) []byte {
	var sb strings.Builder

	converterImports := collectConverterImports(data.TypeName, data.Fields)

	// Header
	sb.WriteString("// Code generated by plugin-morphe-ts-zod-bridge. DO NOT EDIT.\n")

	// Imports
	sb.WriteString(fmt.Sprintf("import type { %s } from '%s';\n", data.TypeName, data.TsTypeImportPath))
	sb.WriteString(fmt.Sprintf("import { %s } from '%s';\n", data.SchemaName, data.ZodSchemaImportPath))
	sb.WriteString("import { z } from 'zod';\n")

	for _, ci := range converterImports {
		sb.WriteString(fmt.Sprintf("import { %s } from '%s';\n", ci.functionName, ci.importPath))
	}

	// Function
	sb.WriteString("\n")
	sb.WriteString(fmt.Sprintf("export function %s(\n", data.FunctionName))
	sb.WriteString(fmt.Sprintf("  source: z.infer<typeof %s>\n", data.SchemaName))
	sb.WriteString(fmt.Sprintf("): %s {\n", data.TypeName))
	sb.WriteString("  return {\n")

	for _, field := range data.Fields {
		valueExpr := renderFieldValue(field)
		if field.Optional {
			sb.WriteString(fmt.Sprintf("    ...(source.%s !== undefined && {\n", field.SourceName))
			sb.WriteString(fmt.Sprintf("      %s: %s,\n", field.TargetName, valueExpr))
			sb.WriteString("    }),\n")
		} else {
			sb.WriteString(fmt.Sprintf("    %s: %s,\n", field.TargetName, valueExpr))
		}
	}

	sb.WriteString("  };\n")
	sb.WriteString("}\n")

	return []byte(sb.String())
}

// renderFieldValue returns the TypeScript expression for a field value.
// Scalar fields produce "source.field_name". Relationship object fields
// produce "convertTarget(source.field_name)" or "source.field_name.map(convertTarget)".
func renderFieldValue(field FieldMapping) string {
	sourceExpr := fmt.Sprintf("source.%s", field.SourceName)
	if field.ConverterFn != "" {
		if field.IsArray {
			return fmt.Sprintf("%s.map(%s)", sourceExpr, field.ConverterFn)
		}
		return fmt.Sprintf("%s(%s)", field.ConverterFn, sourceExpr)
	}
	return sourceExpr
}

// converterImportEntry holds a converter function name and its import path.
type converterImportEntry struct {
	functionName string
	importPath   string
}

// collectConverterImports deduplicates and returns the converter imports
// needed for relationship object fields, excluding self-references (where
// the converter is defined in the same file).
func collectConverterImports(typeName string, fields []FieldMapping) []converterImportEntry {
	selfFn := "convert" + typeName
	seen := make(map[string]bool)
	var imports []converterImportEntry
	for _, f := range fields {
		if f.ConverterFn == "" || f.ConverterFn == selfFn {
			continue
		}
		if seen[f.ConverterFn] {
			continue
		}
		seen[f.ConverterFn] = true
		imports = append(imports, converterImportEntry{
			functionName: f.ConverterFn,
			importPath:   f.ConverterImport,
		})
	}
	return imports
}

// hasAttribute checks if a target attribute string exists in a list of attributes.
func hasAttribute(attributes []string, target string) bool {
	for _, attr := range attributes {
		if attr == target {
			return true
		}
	}
	return false
}
